# ansible.windows.win_feature module – Installs and uninstalls Windows Features on Windows Server
# https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_feature_module.html
# für eine Liste aller Rollen - auf Server => Get-WindowsFeature
#
- name: Serverrolle installieren
  ansible.windows.win_feature:
    # name: Web-Server
    name: "{{ feature_name }}"
    
    # state: present = Installation
    state: present
    
    # include_sub_features: true
    include_sub_features: "{{ include_sub_features_selection }}"

    # include_management_tools: true
    include_management_tools: "{{ include_management_tools_selection }}"
  register: win_feature

- name: Neustart nach Abschluss der Installation
  ansible.windows.win_reboot:
  when: win_feature.reboot_required