# Ansible collection for Active Directory management
# https://docs.ansible.com/ansible/latest/collections/microsoft/ad/index.html#plugins-in-microsoft-ad

# microsoft.ad.membership module – Manage domain/workgroup membership for a Windows host
# https://docs.ansible.com/ansible/latest/collections/microsoft/ad/membership_module.html

- name: Joining Windows domain
  microsoft.ad.membership:
    dns_domain_name: "{{ domain_name }}"
    # hostname: mydomainclient

    # domain_admin_user: adminuser@contoso.local
    domain_admin_user: "{{ domain_admin_user_selection }}"

    # domain_admin_password: Telekom12345!
    domain_admin_password: "{{ domain_password_selection }}" 

    # domain_ou_path: "OU=Windows,OU=Servers,DC=ansible,DC=vagrant"

    # When state=domain, dns_domain_name, domain_admin_user, and domain_admin_password or offline_join_blob must be set.
    # When state=workgroup, workgroup_name must be set.
    state: domain
    reboot: true
  register: domain_state

- name: Neustart nach Domain Join
  ansible.windows.win_reboot:
  when: domain_state.reboot_required

- ansible.windows.win_reboot:
  when: domain_state.reboot_required