# - name: Install xWebAdministration PowerShell Module
#   ansible.windows.win_psmodule:
#     name: xWebAdministration
#     state: present

- name: erforderliche NuGet package provider version installieren
  ansible.windows.win_shell: Find-PackageProvider -Name Nuget -ForceBootstrap -IncludeDependencies -Force

# Powershell Modul installieren um Webserver zu administrieren
# https://www.powershellgallery.com/packages/xWebAdministration/3.3.0
- name: Powershell Modul installieren
  community.windows.win_psmodule:
    name: xWebAdministration
    accept_license: true
    state: present

# ansible.windows.win_dsc module – Invokes a PowerShell DSC configuration
# https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_dsc_module.html

- name: IIS-Website mit Bindung und Authentifizierung erstellen
  ansible.windows.win_dsc:
    resource_name: xWebsite
    Ensure: Present
    Name: Company Intranet
    State: Started
    
    # PhysicalPath: C:\inetpub\wwwroot\meinebeispielwebsite
    PhysicalPath: "{{ IIS_path }}"

    BindingInfo: # Example of a CimInstance[] DSC parameter (list of dicts)
    # - Protocol: https
    #   Port: 1234
    #   CertificateStoreName: MY
    #   CertificateThumbprint: C676A89018C4D5902353545343634F35E6B3A659
    #   HostName: DSCTest
    #   IPAddress: '*'
    #   SSLFlags: '1'
    - Protocol: http
      # Port: 4321
      Port: 80
      IPAddress: '*'
    AuthenticationInfo: # Example of a CimInstance DSC parameter (dict)
      # Anonymous: no
      Anonymous: true
      Basic: true
      Digest: false
      Windows: yes