# Ansible collection for Active Directory management
# https://docs.ansible.com/ansible/latest/collections/microsoft/ad/index.html#plugins-in-microsoft-ad

# https://docs.ansible.com/ansible/latest/collections/microsoft/ad/domain_module.html#ansible-collections-microsoft-ad-domain-module

# - name: Create new domain in a new forest on the target host and reboot
#   microsoft.ad.domain:
#     dns_domain_name: "{{ domain_name }}"
#     safe_mode_password: "{{ domain_password }}"
#     reboot: true

- name: Erstellung Microsoft Active Directory in einem neuen AD-Forest
  microsoft.ad.domain:
    create_dns_delegation: false
    dns_domain_name: "{{ domain_name }}"
    domain_netbios_name: "{{ domain_netbios_name }}"
    safe_mode_password: "{{ domain_password }}"
    
    # Win2003, Win2008, Win2008R2, Win2012, Win2012R2, or WinThreshold
    domain_mode: Win2012R2
    forest_mode: Win2012R2

    sysvol_path: "{{ sysvol_directory }}"
    # sysvol_path: C:\Windows\SYSVOL

    database_path: "{{ ntds_directory }}"
    # database_path: C:\Windows\NTDS

    install_dns: true
    reboot: true
  register: domain_install

- name: Neustart nach Abschluss der Installation
  ansible.windows.win_reboot:
  when: domain_install.reboot_required